// Auto-generated by pre-build.js
// Do not edit this file directly.
export const contentImports: Record<string, Record<string, () => Promise<any>>> = {
  'lorem-ipsum-bog': {
    '01-introduktion.md': () => import('../../../content/lorem-ipsum-bog/01-introduktion.md'),
    '02-klassisk-lorem.md': () => import('../../../content/lorem-ipsum-bog/02-klassisk-lorem.md'),
    '03-moderne-variationer.md': () => import('../../../content/lorem-ipsum-bog/03-moderne-variationer.md'),
    '04-teknisk-lorem.md': () => import('../../../content/lorem-ipsum-bog/04-teknisk-lorem.md'),
    '05-kreativ-lorem.md': () => import('../../../content/lorem-ipsum-bog/05-kreativ-lorem.md'),
    '06-konklusion.md': () => import('../../../content/lorem-ipsum-bog/06-konklusion.md')
  }
};
