// Auto-generated runtime configuration
// This file is generated by the pre-build script
// DO NOT EDIT MANUALLY

export interface ModuleConfig {
  name: string;
  path: string;
  entry: string;
}

export interface CollectionConfig {
  id: string;
  path: string;
  toc: string;
  theme?: any;
  tocData?: {
    title: string;
    description: string;
    author: string;
    version: string;
    chapters: Array<{
      id: string;
      title: string;
      file: string;
      description: string;
    }>;
  };
  pages?: Array<{
    slug: string;
    title: string;
    path: string;
    description?: string;
  }>;
}

export const modules: ModuleConfig[] = [
  {
    "name": "ui-kit",
    "path": "./ui-kit",
    "entry": "src/index.ts"
  }
];

export const collections: CollectionConfig[] = [
  {
    "id": "web-ux-2025",
    "path": "./bog-ux-2025",
    "toc": "toc.yml",
    "tocData": null,
    "theme": {
      "colors": {
        "light": {
          "background": "0 0% 100%",
          "foreground": "222.2 84% 4.9%",
          "card": "0 0% 100%",
          "card-foreground": "222.2 84% 4.9%",
          "popover": "0 0% 100%",
          "popover-foreground": "222.2 84% 4.9%",
          "primary": "210 40% 98%",
          "primary-foreground": "210 40% 9.8%",
          "secondary": "210 40% 96.1%",
          "secondary-foreground": "210 40% 9.8%",
          "muted": "210 40% 96.1%",
          "muted-foreground": "217.2 32.6% 17.5%",
          "accent": "210 40% 96.1%",
          "accent-foreground": "210 40% 9.8%",
          "destructive": "0 84.2% 60.2%",
          "destructive-foreground": "210 40% 98%",
          "border": "214.3 31.8% 91.4%",
          "input": "214.3 31.8% 91.4%",
          "ring": "222.2 84% 4.9%"
        },
        "dark": {
          "background": "222.2 84% 4.9%",
          "foreground": "210 40% 98%",
          "card": "222.2 84% 4.9%",
          "card-foreground": "210 40% 98%",
          "popover": "222.2 84% 4.9%",
          "popover-foreground": "210 40% 98%",
          "primary": "210 40% 9.8%",
          "primary-foreground": "210 40% 98%",
          "secondary": "217.2 32.6% 17.5%",
          "secondary-foreground": "210 40% 98%",
          "muted": "217.2 32.6% 17.5%",
          "muted-foreground": "215 20.2% 65.1%",
          "accent": "217.2 32.6% 17.5%",
          "accent-foreground": "210 40% 98%",
          "destructive": "0 62.8% 30.6%",
          "destructive-foreground": "210 40% 98%",
          "border": "217.2 32.6% 17.5%",
          "input": "217.2 32.6% 17.5%",
          "ring": "215 20.2% 65.1%"
        }
      }
    },
    "pages": []
  },
  {
    "id": "lorem-ipsum-bog",
    "path": "./lorem-ipsum-bog",
    "toc": "toc.yml",
    "tocData": {
      "title": "Lorem Ipsum: En Klassisk Bog",
      "description": "En samling af klassiske Lorem Ipsum tekster med forskellige variationer og stilarter",
      "author": "Cicero & Moderne Forfattere",
      "version": "1.0.0",
      "chapters": [
        {
          "id": "introduktion",
          "title": "Introduktion til Lorem Ipsum",
          "file": "01-introduktion.md",
          "description": "Historien bag den klassiske placeholder-tekst"
        },
        {
          "id": "klassisk-lorem",
          "title": "Klassisk Lorem Ipsum",
          "file": "02-klassisk-lorem.md",
          "description": "Den originale Lorem Ipsum tekst fra Cicero"
        },
        {
          "id": "moderne-variationer",
          "title": "Moderne Variationer",
          "file": "03-moderne-variationer.md",
          "description": "Kreative og moderne tolkninger af Lorem Ipsum"
        },
        {
          "id": "teknisk-lorem",
          "title": "Teknisk Lorem Ipsum",
          "file": "04-teknisk-lorem.md",
          "description": "Lorem Ipsum for tekniske dokumenter og kode"
        },
        {
          "id": "kreativ-lorem",
          "title": "Kreativ Lorem Ipsum",
          "file": "05-kreativ-lorem.md",
          "description": "Kunstneriske og kreative variationer"
        },
        {
          "id": "konklusion",
          "title": "Konklusion",
          "file": "06-konklusion.md",
          "description": "Afsluttende tanker om Lorem Ipsum's betydning"
        }
      ],
      "metadata": {
        "language": "da",
        "category": "reference",
        "tags": [
          "lorem-ipsum",
          "placeholder",
          "tekst",
          "design",
          "typografi"
        ],
        "created": "2024-01-10",
        "updated": "2024-01-10"
      }
    },
    "theme": null,
    "pages": [
      {
        "slug": "introduktion",
        "title": "Introduktion til Lorem Ipsum",
        "path": "01-introduktion.md",
        "description": "Historien bag den klassiske placeholder-tekst"
      },
      {
        "slug": "klassisk-lorem",
        "title": "Klassisk Lorem Ipsum",
        "path": "02-klassisk-lorem.md",
        "description": "Den originale Lorem Ipsum tekst fra Cicero"
      },
      {
        "slug": "moderne-variationer",
        "title": "Moderne Variationer",
        "path": "03-moderne-variationer.md",
        "description": "Kreative og moderne tolkninger af Lorem Ipsum"
      },
      {
        "slug": "teknisk-lorem",
        "title": "Teknisk Lorem Ipsum",
        "path": "04-teknisk-lorem.md",
        "description": "Lorem Ipsum for tekniske dokumenter og kode"
      },
      {
        "slug": "kreativ-lorem",
        "title": "Kreativ Lorem Ipsum",
        "path": "05-kreativ-lorem.md",
        "description": "Kunstneriske og kreative variationer"
      },
      {
        "slug": "konklusion",
        "title": "Konklusion",
        "path": "06-konklusion.md",
        "description": "Afsluttende tanker om Lorem Ipsum's betydning"
      }
    ]
  }
];

// Fallback configuration for development
export const fallbackConfig = {
  modules: [
  {
    "name": "ui-kit",
    "path": "./ui-kit",
    "entry": "src/index.ts"
  }
],
  collections: [
  {
    "id": "web-ux-2025",
    "path": "./bog-ux-2025",
    "toc": "toc.yml",
    "tocData": null,
    "theme": {
      "colors": {
        "light": {
          "background": "0 0% 100%",
          "foreground": "222.2 84% 4.9%",
          "card": "0 0% 100%",
          "card-foreground": "222.2 84% 4.9%",
          "popover": "0 0% 100%",
          "popover-foreground": "222.2 84% 4.9%",
          "primary": "210 40% 98%",
          "primary-foreground": "210 40% 9.8%",
          "secondary": "210 40% 96.1%",
          "secondary-foreground": "210 40% 9.8%",
          "muted": "210 40% 96.1%",
          "muted-foreground": "217.2 32.6% 17.5%",
          "accent": "210 40% 96.1%",
          "accent-foreground": "210 40% 9.8%",
          "destructive": "0 84.2% 60.2%",
          "destructive-foreground": "210 40% 98%",
          "border": "214.3 31.8% 91.4%",
          "input": "214.3 31.8% 91.4%",
          "ring": "222.2 84% 4.9%"
        },
        "dark": {
          "background": "222.2 84% 4.9%",
          "foreground": "210 40% 98%",
          "card": "222.2 84% 4.9%",
          "card-foreground": "210 40% 98%",
          "popover": "222.2 84% 4.9%",
          "popover-foreground": "210 40% 98%",
          "primary": "210 40% 9.8%",
          "primary-foreground": "210 40% 98%",
          "secondary": "217.2 32.6% 17.5%",
          "secondary-foreground": "210 40% 98%",
          "muted": "217.2 32.6% 17.5%",
          "muted-foreground": "215 20.2% 65.1%",
          "accent": "217.2 32.6% 17.5%",
          "accent-foreground": "210 40% 98%",
          "destructive": "0 62.8% 30.6%",
          "destructive-foreground": "210 40% 98%",
          "border": "217.2 32.6% 17.5%",
          "input": "217.2 32.6% 17.5%",
          "ring": "215 20.2% 65.1%"
        }
      }
    },
    "pages": []
  },
  {
    "id": "lorem-ipsum-bog",
    "path": "./lorem-ipsum-bog",
    "toc": "toc.yml",
    "tocData": {
      "title": "Lorem Ipsum: En Klassisk Bog",
      "description": "En samling af klassiske Lorem Ipsum tekster med forskellige variationer og stilarter",
      "author": "Cicero & Moderne Forfattere",
      "version": "1.0.0",
      "chapters": [
        {
          "id": "introduktion",
          "title": "Introduktion til Lorem Ipsum",
          "file": "01-introduktion.md",
          "description": "Historien bag den klassiske placeholder-tekst"
        },
        {
          "id": "klassisk-lorem",
          "title": "Klassisk Lorem Ipsum",
          "file": "02-klassisk-lorem.md",
          "description": "Den originale Lorem Ipsum tekst fra Cicero"
        },
        {
          "id": "moderne-variationer",
          "title": "Moderne Variationer",
          "file": "03-moderne-variationer.md",
          "description": "Kreative og moderne tolkninger af Lorem Ipsum"
        },
        {
          "id": "teknisk-lorem",
          "title": "Teknisk Lorem Ipsum",
          "file": "04-teknisk-lorem.md",
          "description": "Lorem Ipsum for tekniske dokumenter og kode"
        },
        {
          "id": "kreativ-lorem",
          "title": "Kreativ Lorem Ipsum",
          "file": "05-kreativ-lorem.md",
          "description": "Kunstneriske og kreative variationer"
        },
        {
          "id": "konklusion",
          "title": "Konklusion",
          "file": "06-konklusion.md",
          "description": "Afsluttende tanker om Lorem Ipsum's betydning"
        }
      ],
      "metadata": {
        "language": "da",
        "category": "reference",
        "tags": [
          "lorem-ipsum",
          "placeholder",
          "tekst",
          "design",
          "typografi"
        ],
        "created": "2024-01-10",
        "updated": "2024-01-10"
      }
    },
    "theme": null,
    "pages": [
      {
        "slug": "introduktion",
        "title": "Introduktion til Lorem Ipsum",
        "path": "01-introduktion.md",
        "description": "Historien bag den klassiske placeholder-tekst"
      },
      {
        "slug": "klassisk-lorem",
        "title": "Klassisk Lorem Ipsum",
        "path": "02-klassisk-lorem.md",
        "description": "Den originale Lorem Ipsum tekst fra Cicero"
      },
      {
        "slug": "moderne-variationer",
        "title": "Moderne Variationer",
        "path": "03-moderne-variationer.md",
        "description": "Kreative og moderne tolkninger af Lorem Ipsum"
      },
      {
        "slug": "teknisk-lorem",
        "title": "Teknisk Lorem Ipsum",
        "path": "04-teknisk-lorem.md",
        "description": "Lorem Ipsum for tekniske dokumenter og kode"
      },
      {
        "slug": "kreativ-lorem",
        "title": "Kreativ Lorem Ipsum",
        "path": "05-kreativ-lorem.md",
        "description": "Kunstneriske og kreative variationer"
      },
      {
        "slug": "konklusion",
        "title": "Konklusion",
        "path": "06-konklusion.md",
        "description": "Afsluttende tanker om Lorem Ipsum's betydning"
      }
    ]
  }
]
};
