// Auto-generated runtime configuration
// This file is generated by the pre-build script
// DO NOT EDIT MANUALLY

export interface ModuleConfig {
  name: string;
  path: string;
  entry: string;
}

export interface CollectionConfig {
  id: string;
  path: string;
  toc: string;
  tocData?: {
    title: string;
    description: string;
    author: string;
    version: string;
    chapters: Array<{
      id: string;
      title: string;
      file: string;
      description: string;
    }>;
  };
  pages?: Array<{
    slug: string;
    title: string;
    path: string;
    description?: string;
  }>;
}

export const modules: ModuleConfig[] = [
  {
    "name": "ui-kit",
    "path": "./ui-kit",
    "entry": "src/index.ts"
  }
];

export const collections: CollectionConfig[] = [
  {
    "id": "web-ux-2025",
    "path": "./bog-ux-2025",
    "toc": "toc.yml"
  },
  {
    "id": "lorem-ipsum-bog",
    "path": "./lorem-ipsum-bog",
    "toc": "toc.yml",
    "tocData": {
      "title": "Lorem Ipsum: En Klassisk Bog",
      "description": "En samling af klassiske Lorem Ipsum tekster med forskellige variationer og stilarter",
      "author": "Cicero & Moderne Forfattere",
      "version": "1.0.0",
      "chapters": [
        {
          "id": "introduktion",
          "title": "Introduktion til Lorem Ipsum",
          "file": "01-introduktion.mdx",
          "description": "Historien bag den klassiske placeholder-tekst"
        },
        {
          "id": "klassisk-lorem",
          "title": "Klassisk Lorem Ipsum",
          "file": "02-klassisk-lorem.mdx",
          "description": "Den originale Lorem Ipsum tekst fra Cicero"
        },
        {
          "id": "moderne-variationer",
          "title": "Moderne Variationer",
          "file": "03-moderne-variationer.mdx",
          "description": "Kreative og moderne tolkninger af Lorem Ipsum"
        },
        {
          "id": "teknisk-lorem",
          "title": "Teknisk Lorem Ipsum",
          "file": "04-teknisk-lorem.mdx",
          "description": "Lorem Ipsum for tekniske dokumenter og kode"
        },
        {
          "id": "kreativ-lorem",
          "title": "Kreativ Lorem Ipsum",
          "file": "05-kreativ-lorem.mdx",
          "description": "Kunstneriske og kreative variationer"
        },
        {
          "id": "konklusion",
          "title": "Konklusion",
          "file": "06-konklusion.mdx",
          "description": "Afsluttende tanker om Lorem Ipsum's betydning"
        }
      ],
      "metadata": {
        "language": "da",
        "category": "reference",
        "tags": [
          "lorem-ipsum",
          "placeholder",
          "tekst",
          "design",
          "typografi"
        ],
        "created": "2024-01-10",
        "updated": "2024-01-10"
      }
    },
    "pages": [
      {
        "slug": "introduktion",
        "title": "Introduktion til Lorem Ipsum",
        "path": "01-introduktion.mdx",
        "description": "Historien bag den klassiske placeholder-tekst"
      },
      {
        "slug": "klassisk-lorem",
        "title": "Klassisk Lorem Ipsum",
        "path": "02-klassisk-lorem.mdx",
        "description": "Den originale Lorem Ipsum tekst fra Cicero"
      },
      {
        "slug": "moderne-variationer",
        "title": "Moderne Variationer",
        "path": "03-moderne-variationer.mdx",
        "description": "Kreative og moderne tolkninger af Lorem Ipsum"
      },
      {
        "slug": "teknisk-lorem",
        "title": "Teknisk Lorem Ipsum",
        "path": "04-teknisk-lorem.mdx",
        "description": "Lorem Ipsum for tekniske dokumenter og kode"
      },
      {
        "slug": "kreativ-lorem",
        "title": "Kreativ Lorem Ipsum",
        "path": "05-kreativ-lorem.mdx",
        "description": "Kunstneriske og kreative variationer"
      },
      {
        "slug": "konklusion",
        "title": "Konklusion",
        "path": "06-konklusion.mdx",
        "description": "Afsluttende tanker om Lorem Ipsum's betydning"
      }
    ]
  }
];

// Fallback configuration for development
export const fallbackConfig = {
  modules: [
  {
    "name": "ui-kit",
    "path": "./ui-kit",
    "entry": "src/index.ts"
  }
],
  collections: [
  {
    "id": "web-ux-2025",
    "path": "./bog-ux-2025",
    "toc": "toc.yml"
  },
  {
    "id": "lorem-ipsum-bog",
    "path": "./lorem-ipsum-bog",
    "toc": "toc.yml",
    "tocData": {
      "title": "Lorem Ipsum: En Klassisk Bog",
      "description": "En samling af klassiske Lorem Ipsum tekster med forskellige variationer og stilarter",
      "author": "Cicero & Moderne Forfattere",
      "version": "1.0.0",
      "chapters": [
        {
          "id": "introduktion",
          "title": "Introduktion til Lorem Ipsum",
          "file": "01-introduktion.mdx",
          "description": "Historien bag den klassiske placeholder-tekst"
        },
        {
          "id": "klassisk-lorem",
          "title": "Klassisk Lorem Ipsum",
          "file": "02-klassisk-lorem.mdx",
          "description": "Den originale Lorem Ipsum tekst fra Cicero"
        },
        {
          "id": "moderne-variationer",
          "title": "Moderne Variationer",
          "file": "03-moderne-variationer.mdx",
          "description": "Kreative og moderne tolkninger af Lorem Ipsum"
        },
        {
          "id": "teknisk-lorem",
          "title": "Teknisk Lorem Ipsum",
          "file": "04-teknisk-lorem.mdx",
          "description": "Lorem Ipsum for tekniske dokumenter og kode"
        },
        {
          "id": "kreativ-lorem",
          "title": "Kreativ Lorem Ipsum",
          "file": "05-kreativ-lorem.mdx",
          "description": "Kunstneriske og kreative variationer"
        },
        {
          "id": "konklusion",
          "title": "Konklusion",
          "file": "06-konklusion.mdx",
          "description": "Afsluttende tanker om Lorem Ipsum's betydning"
        }
      ],
      "metadata": {
        "language": "da",
        "category": "reference",
        "tags": [
          "lorem-ipsum",
          "placeholder",
          "tekst",
          "design",
          "typografi"
        ],
        "created": "2024-01-10",
        "updated": "2024-01-10"
      }
    },
    "pages": [
      {
        "slug": "introduktion",
        "title": "Introduktion til Lorem Ipsum",
        "path": "01-introduktion.mdx",
        "description": "Historien bag den klassiske placeholder-tekst"
      },
      {
        "slug": "klassisk-lorem",
        "title": "Klassisk Lorem Ipsum",
        "path": "02-klassisk-lorem.mdx",
        "description": "Den originale Lorem Ipsum tekst fra Cicero"
      },
      {
        "slug": "moderne-variationer",
        "title": "Moderne Variationer",
        "path": "03-moderne-variationer.mdx",
        "description": "Kreative og moderne tolkninger af Lorem Ipsum"
      },
      {
        "slug": "teknisk-lorem",
        "title": "Teknisk Lorem Ipsum",
        "path": "04-teknisk-lorem.mdx",
        "description": "Lorem Ipsum for tekniske dokumenter og kode"
      },
      {
        "slug": "kreativ-lorem",
        "title": "Kreativ Lorem Ipsum",
        "path": "05-kreativ-lorem.mdx",
        "description": "Kunstneriske og kreative variationer"
      },
      {
        "slug": "konklusion",
        "title": "Konklusion",
        "path": "06-konklusion.mdx",
        "description": "Afsluttende tanker om Lorem Ipsum's betydning"
      }
    ]
  }
]
};
